"""Add static fields to leads (name, last_name, phone, company, company_url)

Revision ID: 2fbf1e3a5c42
Revises: d45a44c66dbd
Create Date: 2026-04-11 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbf1e3a5c42'
down_revision: Union[str, Sequence[str], None] = 'd45a44c66dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('name', sa.String(length=255), nullable=False, server_default='Unknown'))
    op.add_column('leads', sa.Column('last_name', sa.String(length=255), nullable=False, server_default='Unknown'))
    op.add_column('leads', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('company_url', sa.String(length=2048), nullable=True))
    op.create_index(op.f('ix_leads_name'), 'leads', ['name'], unique=False)
    op.create_index(op.f('ix_leads_last_name'), 'leads', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_last_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_name'), table_name='leads')
    op.drop_column('leads', 'company_url')
    op.drop_column('leads', 'company')
    op.drop_column('leads', 'phone')
    op.drop_column('leads', 'last_name')
    op.drop_column('leads', 'name')
    # ### end Alembic commands ###
