"""Add lead_field_mapping to forms

Revision ID: 3c8d2e9f4a51
Revises: 2fbf1e3a5c42
Create Date: 2026-04-11 10:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8d2e9f4a51'
down_revision: Union[str, Sequence[str], None] = '2fbf1e3a5c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('lead_field_mapping', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'lead_field_mapping')
    # ### end Alembic commands ###
