"""Add display_as_steps column to forms

Revision ID: d45a44c66dbd
Revises: b42018cef8f2
Create Date: 2026-04-09 14:18:27.446904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45a44c66dbd'
down_revision: Union[str, Sequence[str], None] = 'b42018cef8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('display_as_steps', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'display_as_steps')
    # ### end Alembic commands ###
